# Generated by Django 5.2.3 on 2025-07-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='unique_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
